/**
 * One-off codegen: extracts move flags (contact/bite/sound/punch/bullet/
 * pulse/slicing/wind) from @smogon/calc's bundled Gen 9 Showdown movedex
 * and writes them to a static config file.
 *
 * Not run as part of the build - regenerate manually if @smogon/calc's
 * bundled move data changes:
 *   npx tsx scripts/generateMoveFlags.ts
 *
 * Why generate instead of importing @smogon/calc at runtime: that package
 * is intentionally lazy-loaded only for the Calc tab (~500KB chunk, see
 * useDamageCalc.ts) to keep it out of the main bundle. Move flags need to
 * be available app-wide (tooltips, move pickers), so this snapshot avoids
 * pulling the whole calc engine back into the main chunk just for 8 boolean
 * flags per move.
 */
import { Generations } from '@smogon/calc';
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

function normalizeNameForAPI(name: string): string {
  return name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/[\s_]+/g, '-');
}

const gen = Generations.get(9);
const table: Record<string, string[]> = {};

for (const move of gen.moves) {
  const flagKeys = Object.entries(move.flags)
    .filter(([, v]) => v)
    .map(([k]) => k)
    .sort();
  if (flagKeys.length > 0) {
    table[normalizeNameForAPI(move.name)] = flagKeys;
  }
}

const sortedTable = Object.fromEntries(Object.entries(table).sort(([a], [b]) => a.localeCompare(b)));

const output = `/**
 * AUTO-GENERATED by scripts/generateMoveFlags.ts - do not hand-edit.
 * Regenerate with: npx tsx scripts/generateMoveFlags.ts
 *
 * Source: @smogon/calc's bundled Gen 9 Showdown movedex (a static
 * snapshot, not a runtime dependency - see the script header for why).
 * Keyed by the same normalized move slug convention as
 * services/pokeapiService.ts's normalizeNameForAPI. Only moves with at
 * least one flag are included; a move absent from this table has none.
 */
export const MOVE_FLAGS_DATA: Record<string, string[]> = ${JSON.stringify(sortedTable, null, 2)};
`;

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = join(__dirname, '../src/renderer/config/moveFlagsData.generated.ts');
writeFileSync(outPath, output);
console.log(`Wrote ${Object.keys(sortedTable).length} moves' flags to ${outPath}`);
