/**
 * One-off codegen: extracts multi-hit move data (hit-count range) from
 * @smogon/calc's bundled Gen 9 Showdown movedex and writes it to a static
 * config file - same source/approach as generateMoveFlags.ts (see that
 * script's header for why a generated snapshot instead of a runtime
 * dependency).
 *
 * Not run as part of the build - regenerate manually if @smogon/calc's
 * bundled move data changes:
 *   npx tsx scripts/generateMultiHitMoves.ts
 *
 * Showdown's `multihit` field is either a fixed count (number) or a
 * [min, max] range; `multiaccuracy` marks moves where each hit rolls
 * accuracy independently (Triple Kick/Axel, Population Bomb) rather than
 * one accuracy check for the whole flurry - for those, a fixed `multihit`
 * count is the *maximum* possible hits, not a guaranteed count, so it's
 * normalized to a {min: 1, max} range here same as the array-form moves,
 * rather than left as a single number that would misrepresent it as fixed.
 */
import { Generations } from '@smogon/calc';
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

function normalizeNameForAPI(name: string): string {
  return name.toLowerCase().trim().replace(/\s+/g, '-');
}

const gen = Generations.get(9);
const table: Record<string, { min: number; max: number }> = {};

for (const move of gen.moves) {
  if (!move.multihit) continue;
  const range = Array.isArray(move.multihit)
    ? { min: move.multihit[0], max: move.multihit[1] }
    : move.multiaccuracy
      ? { min: 1, max: move.multihit }
      : { min: move.multihit, max: move.multihit };
  table[normalizeNameForAPI(move.name)] = range;
}

const sortedTable = Object.fromEntries(Object.entries(table).sort(([a], [b]) => a.localeCompare(b)));

const output = `/**
 * AUTO-GENERATED by scripts/generateMultiHitMoves.ts - do not hand-edit.
 * Regenerate with: npx tsx scripts/generateMultiHitMoves.ts
 *
 * Source: @smogon/calc's bundled Gen 9 Showdown movedex (a static
 * snapshot, not a runtime dependency - see the script header for why).
 * Keyed by the same normalized move slug convention as
 * config/moveStatEffects.ts (lowercase, spaces -> hyphens). A move absent
 * from this table isn't multi-hit.
 */
export const MULTI_HIT_MOVES_DATA: Record<string, { min: number; max: number }> = ${JSON.stringify(sortedTable, null, 2)};
`;

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = join(__dirname, '../src/renderer/config/multiHitMoves.generated.ts');
writeFileSync(outPath, output);
console.log(`Wrote ${Object.keys(sortedTable).length} multi-hit moves to ${outPath}`);
