/**
 * AUTO-GENERATED by scripts/generateTeamSheetLayout.ts - do not hand-edit.
 * Regenerate with: npx tsx scripts/generateTeamSheetLayout.ts
 *
 * Field draw positions (PDF points, origin bottom-left) for
 * public/vg-team-list-template.pdf, derived from the template's own text
 * layer - see the generator script's header for the derivation approach and
 * the one coordinate (Age Division checkboxes) that's an estimate rather
 * than an exact measurement.
 */
export interface TeamSheetFieldPos { x: number; y: number; size: number }
export interface TeamSheetPokemonSlot {
  species: TeamSheetFieldPos;
  statAlignment: TeamSheetFieldPos;
  ability: TeamSheetFieldPos;
  heldItem: TeamSheetFieldPos;
  move1: TeamSheetFieldPos;
  move2: TeamSheetFieldPos;
  move3: TeamSheetFieldPos;
  move4: TeamSheetFieldPos;
}
export interface TeamSheetPageLayout {
  playerName: TeamSheetFieldPos;
  ageDivision: { juniors: TeamSheetFieldPos; seniors: TeamSheetFieldPos; masters: TeamSheetFieldPos };
  trainerNameInGame: TeamSheetFieldPos;
  battleTeamNumberName: TeamSheetFieldPos;
  switchProfileName: TeamSheetFieldPos;
  pokemonSlots: TeamSheetPokemonSlot[];
}
export interface TeamSheetStaffPageLayout extends TeamSheetPageLayout {
  playerId: TeamSheetFieldPos;
  dateOfBirth: { month: TeamSheetFieldPos; day: TeamSheetFieldPos; year: TeamSheetFieldPos };
  supportId: TeamSheetFieldPos;
}
export const TEAM_SHEET_LAYOUT: { page0: TeamSheetStaffPageLayout; page1: TeamSheetPageLayout } = {
  "page0": {
    "playerName": {
      "x": 142.4,
      "y": 706.4,
      "size": 8
    },
    "ageDivision": {
      "juniors": {
        "x": 430.3,
        "y": 706.4,
        "size": 8
      },
      "seniors": {
        "x": 482.4,
        "y": 706.4,
        "size": 8
      },
      "masters": {
        "x": 533.5,
        "y": 706.4,
        "size": 8
      }
    },
    "trainerNameInGame": {
      "x": 142.5,
      "y": 684.3,
      "size": 8
    },
    "battleTeamNumberName": {
      "x": 142.6,
      "y": 664.4,
      "size": 8
    },
    "switchProfileName": {
      "x": 142.5,
      "y": 639.9,
      "size": 8
    },
    "playerId": {
      "x": 434.7,
      "y": 684.3,
      "size": 8
    },
    "dateOfBirth": {
      "month": {
        "x": 434.7,
        "y": 664.4,
        "size": 8
      },
      "day": {
        "x": 488.3,
        "y": 664.4,
        "size": 8
      },
      "year": {
        "x": 544.1,
        "y": 664.4,
        "size": 8
      }
    },
    "supportId": {
      "x": 434.6,
      "y": 639.9,
      "size": 8
    },
    "pokemonSlots": [
      {
        "species": {
          "x": 86.1,
          "y": 610.7,
          "size": 7
        },
        "statAlignment": {
          "x": 86.7,
          "y": 584.6,
          "size": 7
        },
        "ability": {
          "x": 86.1,
          "y": 559.8,
          "size": 7
        },
        "heldItem": {
          "x": 86.1,
          "y": 536.6,
          "size": 7
        },
        "move1": {
          "x": 86.1,
          "y": 513.4,
          "size": 7
        },
        "move2": {
          "x": 86.1,
          "y": 490.3,
          "size": 7
        },
        "move3": {
          "x": 86.1,
          "y": 467.1,
          "size": 7
        },
        "move4": {
          "x": 86.1,
          "y": 443.9,
          "size": 7
        }
      },
      {
        "species": {
          "x": 86.1,
          "y": 409.3,
          "size": 7
        },
        "statAlignment": {
          "x": 86.7,
          "y": 383.2,
          "size": 7
        },
        "ability": {
          "x": 86.1,
          "y": 358.4,
          "size": 7
        },
        "heldItem": {
          "x": 86.1,
          "y": 335.2,
          "size": 7
        },
        "move1": {
          "x": 86.1,
          "y": 312.1,
          "size": 7
        },
        "move2": {
          "x": 86.1,
          "y": 288.9,
          "size": 7
        },
        "move3": {
          "x": 86.1,
          "y": 265.7,
          "size": 7
        },
        "move4": {
          "x": 86.1,
          "y": 242.6,
          "size": 7
        }
      },
      {
        "species": {
          "x": 86.1,
          "y": 207.9,
          "size": 7
        },
        "statAlignment": {
          "x": 86.7,
          "y": 181.8,
          "size": 7
        },
        "ability": {
          "x": 86.1,
          "y": 157,
          "size": 7
        },
        "heldItem": {
          "x": 86.1,
          "y": 133.8,
          "size": 7
        },
        "move1": {
          "x": 86.1,
          "y": 110.7,
          "size": 7
        },
        "move2": {
          "x": 86.1,
          "y": 87.5,
          "size": 7
        },
        "move3": {
          "x": 86.1,
          "y": 65.9,
          "size": 7
        },
        "move4": {
          "x": 86.1,
          "y": 44.2,
          "size": 7
        }
      },
      {
        "species": {
          "x": 378.2,
          "y": 610.7,
          "size": 7
        },
        "statAlignment": {
          "x": 378.8,
          "y": 584.6,
          "size": 7
        },
        "ability": {
          "x": 378.2,
          "y": 559.8,
          "size": 7
        },
        "heldItem": {
          "x": 378.2,
          "y": 536.6,
          "size": 7
        },
        "move1": {
          "x": 378.2,
          "y": 513.4,
          "size": 7
        },
        "move2": {
          "x": 378.2,
          "y": 490.3,
          "size": 7
        },
        "move3": {
          "x": 378.2,
          "y": 467.1,
          "size": 7
        },
        "move4": {
          "x": 378.2,
          "y": 443.9,
          "size": 7
        }
      },
      {
        "species": {
          "x": 378.2,
          "y": 409.3,
          "size": 7
        },
        "statAlignment": {
          "x": 378.8,
          "y": 383.2,
          "size": 7
        },
        "ability": {
          "x": 378.2,
          "y": 358.4,
          "size": 7
        },
        "heldItem": {
          "x": 378.2,
          "y": 335.2,
          "size": 7
        },
        "move1": {
          "x": 378.2,
          "y": 312.1,
          "size": 7
        },
        "move2": {
          "x": 378.2,
          "y": 288.9,
          "size": 7
        },
        "move3": {
          "x": 378.2,
          "y": 265.7,
          "size": 7
        },
        "move4": {
          "x": 378.2,
          "y": 242.6,
          "size": 7
        }
      },
      {
        "species": {
          "x": 378.2,
          "y": 207.9,
          "size": 7
        },
        "statAlignment": {
          "x": 378.8,
          "y": 181.8,
          "size": 7
        },
        "ability": {
          "x": 378.2,
          "y": 157,
          "size": 7
        },
        "heldItem": {
          "x": 378.2,
          "y": 133.8,
          "size": 7
        },
        "move1": {
          "x": 378.2,
          "y": 110.7,
          "size": 7
        },
        "move2": {
          "x": 378.2,
          "y": 87.5,
          "size": 7
        },
        "move3": {
          "x": 378.2,
          "y": 65.9,
          "size": 7
        },
        "move4": {
          "x": 378.2,
          "y": 44.2,
          "size": 7
        }
      }
    ]
  },
  "page1": {
    "playerName": {
      "x": 142.4,
      "y": 708.2,
      "size": 8
    },
    "ageDivision": {
      "juniors": {
        "x": 430.3,
        "y": 708.2,
        "size": 8
      },
      "seniors": {
        "x": 482.4,
        "y": 708.2,
        "size": 8
      },
      "masters": {
        "x": 533.5,
        "y": 708.2,
        "size": 8
      }
    },
    "trainerNameInGame": {
      "x": 142.5,
      "y": 686.1,
      "size": 8
    },
    "battleTeamNumberName": {
      "x": 142.6,
      "y": 664.8,
      "size": 8
    },
    "switchProfileName": {
      "x": 142.5,
      "y": 641.7,
      "size": 8
    },
    "pokemonSlots": [
      {
        "species": {
          "x": 86.1,
          "y": 612.9,
          "size": 7
        },
        "statAlignment": {
          "x": 86.7,
          "y": 586.9,
          "size": 7
        },
        "ability": {
          "x": 86.1,
          "y": 562.1,
          "size": 7
        },
        "heldItem": {
          "x": 86.1,
          "y": 538.9,
          "size": 7
        },
        "move1": {
          "x": 86.1,
          "y": 515.7,
          "size": 7
        },
        "move2": {
          "x": 86.1,
          "y": 492.6,
          "size": 7
        },
        "move3": {
          "x": 86.1,
          "y": 469.4,
          "size": 7
        },
        "move4": {
          "x": 86.1,
          "y": 446.2,
          "size": 7
        }
      },
      {
        "species": {
          "x": 86.1,
          "y": 411.6,
          "size": 7
        },
        "statAlignment": {
          "x": 86.7,
          "y": 385.5,
          "size": 7
        },
        "ability": {
          "x": 86.1,
          "y": 360.6,
          "size": 7
        },
        "heldItem": {
          "x": 86.1,
          "y": 337.5,
          "size": 7
        },
        "move1": {
          "x": 86.1,
          "y": 314.3,
          "size": 7
        },
        "move2": {
          "x": 86.1,
          "y": 291.2,
          "size": 7
        },
        "move3": {
          "x": 86.1,
          "y": 268,
          "size": 7
        },
        "move4": {
          "x": 86.1,
          "y": 244.8,
          "size": 7
        }
      },
      {
        "species": {
          "x": 86.1,
          "y": 210.1,
          "size": 7
        },
        "statAlignment": {
          "x": 86.7,
          "y": 184.1,
          "size": 7
        },
        "ability": {
          "x": 86.1,
          "y": 159.3,
          "size": 7
        },
        "heldItem": {
          "x": 86.1,
          "y": 136.1,
          "size": 7
        },
        "move1": {
          "x": 86.1,
          "y": 112.9,
          "size": 7
        },
        "move2": {
          "x": 86.1,
          "y": 89.8,
          "size": 7
        },
        "move3": {
          "x": 86.1,
          "y": 66.6,
          "size": 7
        },
        "move4": {
          "x": 86.1,
          "y": 43.4,
          "size": 7
        }
      },
      {
        "species": {
          "x": 378.2,
          "y": 612.9,
          "size": 7
        },
        "statAlignment": {
          "x": 378.8,
          "y": 586.9,
          "size": 7
        },
        "ability": {
          "x": 378.2,
          "y": 562.1,
          "size": 7
        },
        "heldItem": {
          "x": 378.2,
          "y": 538.9,
          "size": 7
        },
        "move1": {
          "x": 378.2,
          "y": 515.7,
          "size": 7
        },
        "move2": {
          "x": 378.2,
          "y": 492.6,
          "size": 7
        },
        "move3": {
          "x": 378.2,
          "y": 469.4,
          "size": 7
        },
        "move4": {
          "x": 378.2,
          "y": 446.2,
          "size": 7
        }
      },
      {
        "species": {
          "x": 378.2,
          "y": 411.6,
          "size": 7
        },
        "statAlignment": {
          "x": 378.8,
          "y": 385.5,
          "size": 7
        },
        "ability": {
          "x": 378.2,
          "y": 360.6,
          "size": 7
        },
        "heldItem": {
          "x": 378.2,
          "y": 337.5,
          "size": 7
        },
        "move1": {
          "x": 378.2,
          "y": 314.3,
          "size": 7
        },
        "move2": {
          "x": 378.2,
          "y": 291.2,
          "size": 7
        },
        "move3": {
          "x": 378.2,
          "y": 268,
          "size": 7
        },
        "move4": {
          "x": 378.2,
          "y": 244.8,
          "size": 7
        }
      },
      {
        "species": {
          "x": 378.2,
          "y": 210.1,
          "size": 7
        },
        "statAlignment": {
          "x": 378.8,
          "y": 184.1,
          "size": 7
        },
        "ability": {
          "x": 378.2,
          "y": 159.3,
          "size": 7
        },
        "heldItem": {
          "x": 378.2,
          "y": 136.1,
          "size": 7
        },
        "move1": {
          "x": 378.2,
          "y": 112.9,
          "size": 7
        },
        "move2": {
          "x": 378.2,
          "y": 89.8,
          "size": 7
        },
        "move3": {
          "x": 378.2,
          "y": 66.6,
          "size": 7
        },
        "move4": {
          "x": 378.2,
          "y": 43.4,
          "size": 7
        }
      }
    ]
  }
};
