/**
 * VGC Data Configuration
 * Comprehensive lists of VGC-legal items and commonly used moves
 * Static config file per architecture rules - no inline data in components
 */

/**
 * Comprehensive VGC-legal held items
 * Organized by category for better UX
 */
export const VGC_ITEMS = [
  // Choice Items
  'Choice Band',
  'Choice Scarf',
  'Choice Specs',
  
  // Defensive Items
  'Assault Vest',
  'Focus Sash',
  'Leftovers',
  'Sitrus Berry',
  'Rocky Helmet',
  'Safety Goggles',
  'Clear Amulet',
  'Covert Cloak',
  
  // Offensive Items
  'Life Orb',
  'Expert Belt',
  'Muscle Band',
  'Wise Glasses',
  
  // Type-Boosting Items
  'Charcoal',
  'Mystic Water',
  'Miracle Seed',
  'Magnet',
  'Never-Melt Ice',
  'Black Belt',
  'Poison Barb',
  'Soft Sand',
  'Sharp Beak',
  'Twisted Spoon',
  'Silver Powder',
  'Hard Stone',
  'Spell Tag',
  'Dragon Fang',
  'Black Glasses',
  'Metal Coat',
  'Fairy Feather',
  
  // Berries
  'Aguav Berry',
  'Figy Berry',
  'Iapapa Berry',
  'Mago Berry',
  'Wiki Berry',
  'Lum Berry',
  'Chesto Berry',
  'Pecha Berry',
  'Rawst Berry',
  'Aspear Berry',
  'Persim Berry',
  'Chilan Berry',
  'Occa Berry',
  'Passho Berry',
  'Wacan Berry',
  'Rindo Berry',
  'Yache Berry',
  'Chople Berry',
  'Kebia Berry',
  'Shuca Berry',
  'Coba Berry',
  'Payapa Berry',
  'Tanga Berry',
  'Charti Berry',
  'Kasib Berry',
  'Haban Berry',
  'Colbur Berry',
  'Babiri Berry',
  'Roseli Berry',
  
  // Utility Items
  'Eviolite',
  'Mental Herb',
  'White Herb',
  'Power Herb',
  'Mirror Herb',
  'Loaded Dice',
  'Weakness Policy',
  'Throat Spray',
  'Room Service',
  'Eject Button',
  'Eject Pack',
  'Red Card',
  'Air Balloon',
  'Iron Ball',
  'Lagging Tail',
  'Booster Energy',
  'Protective Pads',
  'Punching Glove',
  
  // Terrain Seeds
  'Electric Seed',
  'Grassy Seed',
  'Misty Seed',
  'Psychic Seed',
  
  // Orbs & Plates
  'Flame Orb',
  'Toxic Orb',
  'Adamant Orb',
  'Lustrous Orb',
  'Griseous Orb',
  
  // Mega Stones & Z-Crystals (if applicable)
  'Abomasite',
  'Absolite',
  'Aerodactylite',
  
  // Misc
  'Bright Powder',
  'Focus Band',
  'King\'s Rock',
  'Razor Claw',
  'Scope Lens',
  'Wide Lens',
  'Zoom Lens',
  'Metronome',
  'Quick Claw',
  'Binding Band',
  'Grip Claw',
] as const;

/**
 * Comprehensive VGC move pool
 * Includes all commonly used moves across formats
 * Organized by usage frequency and type
 */
export const VGC_MOVES = [
  // Priority Moves
  'Protect',
  'Fake Out',
  'Sucker Punch',
  'Aqua Jet',
  'Ice Shard',
  'Mach Punch',
  'Bullet Punch',
  'Shadow Sneak',
  'Accelerock',
  'Extreme Speed',
  'First Impression',
  'Grassy Glide',
  
  // Support Moves
  'Tailwind',
  'Trick Room',
  'Helping Hand',
  'Follow Me',
  'Rage Powder',
  'Wide Guard',
  'Quick Guard',
  'Ally Switch',
  'Coaching',
  'Pollen Puff',
  'Life Dew',
  'Heal Pulse',
  'Floral Healing',
  
  // Status Moves
  'Will-O-Wisp',
  'Thunder Wave',
  'Spore',
  'Sleep Powder',
  'Yawn',
  'Taunt',
  'Encore',
  'Trick',
  'Switcheroo',
  'Parting Shot',
  'Snarl',
  'Icy Wind',
  'Electroweb',
  'Scary Face',
  
  // Stat Boosting
  'Swords Dance',
  'Dragon Dance',
  'Calm Mind',
  'Nasty Plot',
  'Quiver Dance',
  'Bulk Up',
  'Iron Defense',
  'Agility',
  'Rock Polish',
  'Shift Gear',
  
  // Weather & Terrain
  'Rain Dance',
  'Sunny Day',
  'Sandstorm',
  'Hail',
  'Snow',
  'Grassy Terrain',
  'Electric Terrain',
  'Psychic Terrain',
  'Misty Terrain',
  
  // Physical Attacks
  'Earthquake',
  'High Horsepower',
  'Stomping Tantrum',
  'Close Combat',
  'Drain Punch',
  'Sacred Sword',
  'Body Press',
  'Superpower',
  'Hammer Arm',
  'Rock Slide',
  'Stone Edge',
  'Rockfall',
  'Icicle Crash',
  'Ice Punch',
  'Triple Axel',
  'Avalanche',
  'Flare Blitz',
  'Fire Punch',
  'Heat Wave',
  'Blaze Kick',
  'Waterfall',
  'Liquidation',
  'Aqua Cutter',
  'Wave Crash',
  'Thunder Punch',
  'Wild Charge',
  'Zing Zap',
  'Supercell Slam',
  'Giga Impact',
  'Extreme Speed',
  'Double-Edge',
  'Body Slam',
  'Facade',
  'Last Resort',
  'Acrobatics',
  'Brave Bird',
  'Dual Wingbeat',
  'Aerial Ace',
  'Poison Jab',
  'Gunk Shot',
  'Cross Poison',
  'Zen Headbutt',
  'Psychic Fangs',
  'Lunge',
  'Leech Life',
  'U-turn',
  'First Impression',
  'Megahorn',
  'X-Scissor',
  'Outrage',
  'Dragon Claw',
  'Breaking Swipe',
  'Crunch',
  'Knock Off',
  'Throat Chop',
  'Sucker Punch',
  'Iron Head',
  'Heavy Slam',
  'Meteor Mash',
  'Steel Roller',
  'Play Rough',
  'Spirit Break',
  'Dazzling Gleam',
  
  // Special Attacks
  'Draco Meteor',
  'Dragon Pulse',
  'Dragon Energy',
  'Spacial Rend',
  'Roar of Time',
  'Hydro Pump',
  'Surf',
  'Scald',
  'Water Spout',
  'Origin Pulse',
  'Steam Eruption',
  'Muddy Water',
  'Thunderbolt',
  'Thunder',
  'Discharge',
  'Volt Switch',
  'Rising Voltage',
  'Wildbolt Storm',
  'Ice Beam',
  'Blizzard',
  'Freeze-Dry',
  'Glaciate',
  'Flamethrower',
  'Fire Blast',
  'Eruption',
  'Overheat',
  'Heat Wave',
  'Burning Jealousy',
  'Energy Ball',
  'Giga Drain',
  'Leaf Storm',
  'Solar Beam',
  'Solar Blade',
  'Grass Knot',
  'Pollen Puff',
  'Psychic',
  'Psyshock',
  'Expanding Force',
  'Stored Power',
  'Lumina Crash',
  'Sludge Bomb',
  'Sludge Wave',
  'Venoshock',
  'Earth Power',
  'Sandsear Storm',
  'Scorching Sands',
  'Air Slash',
  'Hurricane',
  'Bleakwind Storm',
  'Oblivion Wing',
  'Bug Buzz',
  'Dark Pulse',
  'Foul Play',
  'Snarl',
  'Flash Cannon',
  'Steel Beam',
  'Make It Rain',
  'Moonblast',
  'Dazzling Gleam',
  'Misty Explosion',
  'Strange Steam',
  'Springtide Storm',
  
  // Spread Moves
  'Heat Wave',
  'Discharge',
  'Dazzling Gleam',
  'Muddy Water',
  'Surf',
  'Blizzard',
  'Earthquake',
  'Rock Slide',
  'Icy Wind',
  'Electroweb',
  'Snarl',
  'Glaciate',
  
  // Multi-Hit
  'Population Bomb',
  'Bullet Seed',
  'Icicle Spear',
  'Rock Blast',
  'Bone Rush',
  'Double Iron Bash',
  'Dual Wingbeat',
  'Scale Shot',
  'Surging Strikes',
  'Triple Axel',
  'Triple Kick',
  
  // Signature/Unique
  'Astral Barrage',
  'Behemoth Bash',
  'Behemoth Blade',
  'Collision Course',
  'Electro Drift',
  'Fiery Wrath',
  'Glacial Lance',
  'Jet Punch',
  'Last Respects',
  'Mortal Spin',
  'Rage Fist',
  'Raging Fury',
  'Revival Blessing',
  'Shed Tail',
  'Torch Song',
  'Victory Dance',
  'Wicked Blow',
] as const;

/**
 * Type for VGC items
 */
export type VGCItem = typeof VGC_ITEMS[number];

/**
 * Type for VGC moves
 */
export type VGCMove = typeof VGC_MOVES[number];
