/**
 * VGC Data Configuration
 * Comprehensive lists of VGC-legal items and commonly used moves
 * Static config file per architecture rules - no inline data in components
 */

/**
 * The complete real Pokémon Champions item pool (hold items, Mega Stones,
 * berries) - sourced live from Serebii's dedicated items page, since this is
 * a smaller/different pool than mainline VGC (no Choice items, Assault Vest,
 * Safety Goggles, terrain seeds, etc. exist in this game):
 * https://www.serebii.net/pokemonchampions/items.shtml
 */
export const VGC_ITEMS = [
  // Hold Items
  'Big Root',
  'Black Belt',
  'Black Glasses',
  'Bright Powder',
  'Charcoal',
  'Choice Scarf',
  'Damp Rock',
  'Dragon Fang',
  'Expert Belt',
  'Fairy Feather',
  'Focus Band',
  'Focus Sash',
  'Hard Stone',
  'Heat Rock',
  'Icy Rock',
  'Iron Ball',
  'King\'s Rock',
  'Leftovers',
  'Life Orb',
  'Light Ball',
  'Light Clay',
  'Magnet',
  'Mental Herb',
  'Metal Coat',
  'Metronome',
  'Miracle Seed',
  'Muscle Band',
  'Mystic Water',
  'Never-Melt Ice',
  'Poison Barb',
  'Quick Claw',
  'Scope Lens',
  'Sharp Beak',
  'Shed Shell',
  'Shell Bell',
  'Silk Scarf',
  'Silver Powder',
  'Smooth Rock',
  'Soft Sand',
  'Spell Tag',
  'Twisted Spoon',
  'White Herb',
  'Wide Lens',
  'Wise Glasses',
  'Zoom Lens',

  // Mega Stones
  'Abomasite',
  'Absolite',
  'Aerodactylite',
  'Aggronite',
  'Alakazite',
  'Altarianite',
  'Ampharosite',
  'Audinite',
  'Banettite',
  'Barbaracite',
  'Beedrillite',
  'Blastoisinite',
  'Blazikenite',
  'Cameruptite',
  'Chandelurite',
  'Charizardite X',
  'Charizardite Y',
  'Chesnaughtite',
  'Chimechite',
  'Clefablite',
  'Crabominite',
  'Delphoxite',
  'Dragalgite',
  'Dragoninite',
  'Drampanite',
  'Eelektrossite',
  'Emboarite',
  'Excadrite',
  'Falinksite',
  'Feraligite',
  'Floettite',
  'Froslassite',
  'Galladite',
  'Garchompite',
  'Gardevoirite',
  'Gengarite',
  'Glalitite',
  'Glimmoranite',
  'Golurkite',
  'Greninjite',
  'Gyaradosite',
  'Hawluchanite',
  'Heracronite',
  'Houndoominite',
  'Kangaskhanite',
  'Lopunnite',
  'Lucarionite',
  'Malamarite',
  'Manectite',
  'Mawilite',
  'Medichamite',
  'Meganiumite',
  'Meowsticite',
  'Metagrossite',
  'Pidgeotite',
  'Pinsirite',
  'Pyroarite',
  'Raichunite X',
  'Raichunite Y',
  'Sablenite',
  'Sceptilite',
  'Scizorite',
  'Scolipite',
  'Scovillainite',
  'Scraftinite',
  'Sharpedonite',
  'Skarmorite',
  'Slowbronite',
  'Staraptite',
  'Starminite',
  'Steelixite',
  'Swampertite',
  'Tyranitarite',
  'Venusaurite',
  'Victreebelite',

  // Berries
  'Aspear Berry',
  'Babiri Berry',
  'Charti Berry',
  'Cheri Berry',
  'Chesto Berry',
  'Chilan Berry',
  'Chople Berry',
  'Coba Berry',
  'Colbur Berry',
  'Haban Berry',
  'Kasib Berry',
  'Kebia Berry',
  'Leppa Berry',
  'Lum Berry',
  'Occa Berry',
  'Oran Berry',
  'Passho Berry',
  'Payapa Berry',
  'Pecha Berry',
  'Persim Berry',
  'Rawst Berry',
  'Rindo Berry',
  'Roseli Berry',
  'Shuca Berry',
  'Sitrus Berry',
  'Tanga Berry',
  'Wacan Berry',
  'Yache Berry',
] as const;

/**
 * Comprehensive VGC move pool
 * Includes all commonly used moves across formats
 * Organized by usage frequency and type
 */
export const VGC_MOVES = [
  // Priority Moves
  'Protect',
  'Fake Out',
  'Sucker Punch',
  'Aqua Jet',
  'Ice Shard',
  'Mach Punch',
  'Bullet Punch',
  'Shadow Sneak',
  'Accelerock',
  'Extreme Speed',
  'First Impression',
  'Grassy Glide',
  
  // Support Moves
  'Tailwind',
  'Trick Room',
  'Helping Hand',
  'Follow Me',
  'Rage Powder',
  'Wide Guard',
  'Quick Guard',
  'Ally Switch',
  'Coaching',
  'Pollen Puff',
  'Life Dew',
  'Heal Pulse',
  'Floral Healing',
  
  // Status Moves
  'Will-O-Wisp',
  'Thunder Wave',
  'Spore',
  'Sleep Powder',
  'Yawn',
  'Taunt',
  'Encore',
  'Trick',
  'Switcheroo',
  'Parting Shot',
  'Snarl',
  'Icy Wind',
  'Electroweb',
  'Scary Face',
  
  // Stat Boosting
  'Swords Dance',
  'Dragon Dance',
  'Calm Mind',
  'Nasty Plot',
  'Quiver Dance',
  'Bulk Up',
  'Iron Defense',
  'Agility',
  'Rock Polish',
  'Shift Gear',
  
  // Weather & Terrain
  'Rain Dance',
  'Sunny Day',
  'Sandstorm',
  'Hail',
  'Snow',
  'Grassy Terrain',
  'Electric Terrain',
  'Psychic Terrain',
  'Misty Terrain',
  
  // Physical Attacks
  'Earthquake',
  'High Horsepower',
  'Stomping Tantrum',
  'Close Combat',
  'Drain Punch',
  'Sacred Sword',
  'Body Press',
  'Superpower',
  'Hammer Arm',
  'Rock Slide',
  'Stone Edge',
  'Rockfall',
  'Icicle Crash',
  'Ice Punch',
  'Triple Axel',
  'Avalanche',
  'Flare Blitz',
  'Fire Punch',
  'Heat Wave',
  'Blaze Kick',
  'Waterfall',
  'Liquidation',
  'Aqua Cutter',
  'Wave Crash',
  'Thunder Punch',
  'Wild Charge',
  'Zing Zap',
  'Supercell Slam',
  'Giga Impact',
  'Extreme Speed',
  'Double-Edge',
  'Body Slam',
  'Facade',
  'Last Resort',
  'Acrobatics',
  'Brave Bird',
  'Dual Wingbeat',
  'Aerial Ace',
  'Poison Jab',
  'Gunk Shot',
  'Cross Poison',
  'Zen Headbutt',
  'Psychic Fangs',
  'Lunge',
  'Leech Life',
  'U-turn',
  'First Impression',
  'Megahorn',
  'X-Scissor',
  'Outrage',
  'Dragon Claw',
  'Breaking Swipe',
  'Crunch',
  'Knock Off',
  'Throat Chop',
  'Sucker Punch',
  'Iron Head',
  'Heavy Slam',
  'Meteor Mash',
  'Steel Roller',
  'Play Rough',
  'Spirit Break',
  'Dazzling Gleam',
  
  // Special Attacks
  'Draco Meteor',
  'Dragon Pulse',
  'Dragon Energy',
  'Spacial Rend',
  'Roar of Time',
  'Hydro Pump',
  'Surf',
  'Scald',
  'Water Spout',
  'Origin Pulse',
  'Steam Eruption',
  'Muddy Water',
  'Thunderbolt',
  'Thunder',
  'Discharge',
  'Volt Switch',
  'Rising Voltage',
  'Wildbolt Storm',
  'Ice Beam',
  'Blizzard',
  'Freeze-Dry',
  'Glaciate',
  'Flamethrower',
  'Fire Blast',
  'Eruption',
  'Overheat',
  'Heat Wave',
  'Burning Jealousy',
  'Energy Ball',
  'Giga Drain',
  'Leaf Storm',
  'Solar Beam',
  'Solar Blade',
  'Grass Knot',
  'Pollen Puff',
  'Psychic',
  'Psyshock',
  'Expanding Force',
  'Stored Power',
  'Lumina Crash',
  'Sludge Bomb',
  'Sludge Wave',
  'Venoshock',
  'Earth Power',
  'Sandsear Storm',
  'Scorching Sands',
  'Air Slash',
  'Hurricane',
  'Bleakwind Storm',
  'Oblivion Wing',
  'Bug Buzz',
  'Dark Pulse',
  'Foul Play',
  'Snarl',
  'Flash Cannon',
  'Steel Beam',
  'Make It Rain',
  'Moonblast',
  'Dazzling Gleam',
  'Misty Explosion',
  'Strange Steam',
  'Springtide Storm',
  
  // Spread Moves
  'Heat Wave',
  'Discharge',
  'Dazzling Gleam',
  'Muddy Water',
  'Surf',
  'Blizzard',
  'Earthquake',
  'Rock Slide',
  'Icy Wind',
  'Electroweb',
  'Snarl',
  'Glaciate',
  
  // Multi-Hit
  'Population Bomb',
  'Bullet Seed',
  'Icicle Spear',
  'Rock Blast',
  'Bone Rush',
  'Double Iron Bash',
  'Dual Wingbeat',
  'Scale Shot',
  'Surging Strikes',
  'Triple Axel',
  'Triple Kick',
  
  // Signature/Unique
  'Astral Barrage',
  'Behemoth Bash',
  'Behemoth Blade',
  'Collision Course',
  'Electro Drift',
  'Fiery Wrath',
  'Glacial Lance',
  'Jet Punch',
  'Last Respects',
  'Mortal Spin',
  'Rage Fist',
  'Raging Fury',
  'Revival Blessing',
  'Shed Tail',
  'Torch Song',
  'Victory Dance',
  'Wicked Blow',
] as const;

/**
 * Type for VGC items
 */
export type VGCItem = typeof VGC_ITEMS[number];

/**
 * Type for VGC moves
 */
export type VGCMove = typeof VGC_MOVES[number];
